[build]
  base    = ""
  publish = "website/build"
  command = "export NODE_OPTIONS=--max_old_space_size=4096 && sed -i -e \"s|const baseUrl .*|const baseUrl = '/'|g\" docusaurus.config.js && yarn && cd website && yarn build"
